"""
This contains the notes for the features added, how to run things, 
task delegations, and acknowledgments.
"""

def features_added() -> None:
    """
    The following are the features added in the submission:
    1. Leaderboard on the terminal and game version
    2. Stage data in files (already submitted last December 8)
    3. Docstrings
    4. Autogenerated documentation using Sphinx
    5. Type annotatons
    6. Passing Pyright and mypy strict type-checking
    7. Use of dataclasses and classes in mp1_classes.py
    8. Unit tests in test.py
    9. PEP 8 Compliance
    """
    return

def to_run_things() -> None:
    """
    Go to Linux terminal. Make sure that when you typed ls, 
    you can see the level files and the .py files like game.py
    and others.

    1. To run terminal version of the game:
    run 'python3 mp1.py <level>'

    2. To run the game with the GUI:
    run 'python3 gui.py'

    3. To run the test:
    run 'pytest test.py'

    4. To run Pyright:
    run 'pyright <file>'

    5. To run mypy:
    run 'mypy <file> --strict'

    More details are on the README file.
    """
    return

def task_delegations() -> None:
    """
    John Harry Arciga:
    1. Leaderboard
    2. Stage Data in files
    3. Docstrings
    4. Autogenerated documentation using Sphinx
    5. Passing Pyright and mypy strict type-checking

    David Pagaduan:
    1. Type annotations
    2. Use of dataclasses and classes in mp1_classes.py
    3. Unit tests in test.py
    4. Docstrings
    5. PEP 8 Compliance
    """
    return

def acknowledgments() -> None:
    """
    1. Sphinx Documentation:
    https://www.youtube.com/watch?v=BWIrhgCAae0

    2. Pygame use:
    https://youtu.be/y9VG3Pztok8?si=fFbqIWfeFQjVJQQg
    https://youtu.be/L3ktUWfAMPg?si=vinb08WgA4VTnT61

    3. Pyright and mypy
    https://youtu.be/JdtM8v2GD54?si=XBD7VHmm8UrEX5XO
    https://youtu.be/9gNnhNxra3E?si=6lnpukn0wQ4yw8vB

    4. Pylint for PEP8 documentation
    https://towardsdatascience.com/check-the-quality-of-your-code-with-pylint-f5d829bb441d?gi=89be077e43c6#:~:text=Pylint%20is%20a%20quality%20checker%20for%20Python%20programming,of%20improving%20readability%20and%20consistency%20of%20the%20code.
    https://stackoverflow.com/questions/6879640/how-can-i-configure-pylint-to-check-all-things-pep8-checks

    """
    return
